name: Close Pull Request and Delete Testing Image

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - '**'
      - '!master'
      - '!dev'
  delete:
    branches:
      - '**'
      - '!master'
      - '!dev'

jobs:
  remove_images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Image
        uses: mhl787156/dockerhub-delete-tag-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          organisation: mickeyli789
          image: test-build
          tag: ${{github.event.pull_request.head.ref}}


